#

addons:
  apt:
    packages:
    - g++-4.8

matrix:
  include:
  - language: cpp
    os: linux
    dist: trusty
    compiler: gcc
    env: TARGET=desktop
  - language: cpp
    os: osx
    compiler: clang
    env: TARGET=desktop

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "desktop" ]; then pip install --user urllib3[secure] && pip install --user cpp-coveralls && export CMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS --coverage"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.8; fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "desktop" ]; then ./ci/travis-desktop.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$TARGET" == "desktop" ]; then ./ci/travis-desktop.sh; fi
- sync

after_success:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "desktop" ]; then coveralls --gcov /usr/bin/gcov-4.8 -i src/ --gcov-options '\-lp' > /dev/null; fi
